# Generated by Django 4.2.9 on 2024-02-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('interviewer', 'Interviewer'), ('interviewadmin', 'InterviewAdmin')], max_length=20, null=True),
        ),
    ]
