# Generated by Django 4.2.9 on 2024-02-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_candidate_first_name_alter_candidate_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateavailability',
            name='interview_title',
            field=models.CharField(default='developer', max_length=100),
        ),
    ]
