# Generated by Django 4.2.9 on 2024-02-03 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_remove_candidateavailability_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateavailability',
            name='available_date',
        ),
        migrations.RemoveField(
            model_name='candidateavailability',
            name='available_time_from',
        ),
        migrations.RemoveField(
            model_name='candidateavailability',
            name='available_time_to',
        ),
        migrations.AddField(
            model_name='candidateavailability',
            name='available_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='candidateavailability',
            name='available_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
