# Generated by Django 4.2.9 on 2024-02-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_remove_candidateavailability_available_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateavailability',
            name='interview_title',
            field=models.CharField(default='Available', max_length=100),
        ),
    ]
