# Generated by Django 4.2.9 on 2024-02-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_alter_candidateavailability_interview_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateavailability',
            name='interview_title',
            field=models.CharField(blank=True, default='Available', max_length=100, null=True),
        ),
    ]
