# Generated by Django 4.2.9 on 2024-02-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_alter_candidateavailability_interview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_candidate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='previous_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
