# Generated by Django 4.2.9 on 2024-02-10 07:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0012_candidate_is_candidate_candidate_position_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateAvailability',
            new_name='UserAvailability',
        ),
        migrations.RenameModel(
            old_name='Candidate',
            new_name='UserProfile',
        ),
    ]
